(() => {
 'use strict';
 const data=window.PORTFOLIO,$=(s,root=document)=>root.querySelector(s),motion=matchMedia('(prefers-reduced-motion: reduce)');
 const reduced=motion.matches,genre=id=>data.genres.find(g=>g.id===id);
 const element=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};
 function cover(work,lazy=true){const box=element('div','artwork genre-'+work.genre);if(work.thumbnail){const img=element('img');img.alt=work.title;img.loading=lazy?'lazy':'eager';img.decoding='async';img.draggable=false;img.src=work.thumbnail;img.addEventListener('error',()=>img.remove(),{once:true});box.append(img);}else box.append(element('span','artwork-word',work.title),element('span','artwork-note',genre(work.genre).label));return box;}
 let warmed=false;
 function warmup(){if(warmed)return;warmed=true;for(const href of ['https://www.youtube-nocookie.com','https://www.youtube.com']){const l=element('link');l.rel='preconnect';l.href=href;document.head.append(l);}}
 const feature=data.works.find(w=>w.id===data.featured)||data.works.find(w=>w.youtube.length);
 const hero=element('button','feature-card');hero.type='button';hero.setAttribute('aria-label',feature.title+'を再生');hero.append(cover(feature,false),element('span','feature-play','▶'));hero.addEventListener('click',()=>openWork(feature));hero.addEventListener('pointerenter',warmup,{once:true});$('#featured').append(hero);
 const channels=data.works.flatMap(w=>w.youtube.map((id,i)=>({...w,channelId:w.id+'-'+i,youtube:[id],thumbnail:'https://i.ytimg.com/vi/'+id+'/hqdefault.jpg',title:w.title+(w.youtube.length>1?' / '+String(i+1).padStart(2,'0'):''),original:w})));
 const controllers=[];
 function initBoutique(root){
  const deck=$('.deck',root),tabs=$('.genre-tabs',root),music=root.dataset.collection==='music';let items=[],nodes=[],position=0,target=0,velocity=0,frame=0,last=0,active=true,drag=null,ignoreUntil=0,wheelTimer=null,selected=-1,spacing=280;
  const filters=music?[['music','MUSIC CHANNELS']]:[['all','ALL CHANNELS'],['fantasy','FILMS'],['music','MUSIC VIDEOS']];
  const wrap=(value,n)=>((value+n/2)%n+n)%n-n/2;
  const index=()=>((Math.round(position)%items.length)+items.length)%items.length;
  function measure(){spacing=(nodes[0]?.offsetWidth||Math.min(deck.clientWidth*.68,490))*.73;draw();}
  function metadata(){const i=index(),slot=((Math.round(position)%nodes.length)+nodes.length)%nodes.length;if(i===selected&&nodes[slot]?.getAttribute('aria-current')==='true')return;selected=i;const w=items[i];$('.selected-title',root).textContent=w.title;$('.selected-genre',root).textContent='CH '+String(i%items.length+1).padStart(2,'0')+' / '+genre(w.genre).label;$('.counter',root).textContent=String(i+1).padStart(2,'0')+' / '+String(items.length).padStart(2,'0');nodes.forEach((b,j)=>{b.setAttribute('aria-current',String(slot===j));b.tabIndex=slot===j?0:-1;});}
  function draw(){if(!items.length)return;root.dataset.position=position.toFixed(4);const n=nodes.length;nodes.forEach((b,i)=>{const o=wrap(i-position,n),a=Math.abs(o),visible=a<3;const opacity=visible?Math.max(0,Math.min(1,(3-a)*1.4)):0;b.style.transform=`translate3d(calc(-50% + ${o*spacing}px),${a*18}px,${-a*145}px) rotateY(${-o*17}deg) rotateZ(${o*1.5}deg)`;b.style.opacity=opacity;b.style.zIndex=String(100-Math.round(a*10));b.style.pointerEvents=a<2.2?'auto':'none';b.setAttribute('aria-hidden',String(!visible));});metadata();}
  function tick(now){frame=0;if(!active)return;const dt=Math.min((now-last)/1000||.016,.032);last=now;if(!drag){const force=(target-position)*155-velocity*25;velocity+=force*dt;position+=velocity*dt;if(Math.abs(target-position)<.0005&&Math.abs(velocity)<.003){position=target;velocity=0;draw();return;}}draw();if(!drag)frame=requestAnimationFrame(tick);}
  function animate(){if(motion.matches){position=target;velocity=0;draw();return;}if(!frame&&active){last=performance.now();frame=requestAnimationFrame(tick);}}
  function go(delta){clearTimeout(wheelTimer);target=Math.round(target)+delta;animate();}
  function choose(filter){cancelAnimationFrame(frame);frame=0;items=channels.filter(w=>music?w.genre==='music':filter==='all'||w.genre===filter);position=target=velocity=0;selected=-1;deck.replaceChildren();nodes=Array.from({length:items.length*Math.ceil(8/items.length)},(_,i)=>{const w=items[i%items.length];const b=element('button','tv-card');b.type='button';b.dataset.channel=w.channelId;b.setAttribute('aria-label',w.title+' チャンネルを選択');const screen=element('div','tv-screen');screen.append(cover(w,false),element('span','tv-channel','CH '+String(i%items.length+1).padStart(2,'0')),element('span','tv-play','▶'));const foot=element('div','tv-foot');foot.append(element('span','tv-brand','bianca tv'),element('span','tv-speaker','|||||||'),element('span','tv-knob','✳'));b.append(screen,foot);b.addEventListener('click',()=>{if(Date.now()<ignoreUntil)return;const delta=wrap(i-position,nodes.length);if(Math.abs(delta)<.2)openWork(w);else {target=position+delta;animate();}});b.addEventListener('pointerenter',warmup,{once:true});deck.append(b);return b;});tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));measure();}
  filters.forEach(([id,label])=>{const b=element('button','genre-tab',label);b.type='button';b.dataset.filter=id;b.addEventListener('click',()=>choose(id));tabs.append(b);});
  $('.previous',root).addEventListener('click',()=>go(-1));$('.next',root).addEventListener('click',()=>go(1));$('.play-selected',root).addEventListener('click',()=>openWork(items[index()]));
  root.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();go(e.key==='ArrowRight'?1:-1);}if(e.key==='Escape')root.blur();});
  deck.addEventListener('dragstart',e=>e.preventDefault());
  deck.addEventListener('pointerdown',e=>{if(e.button!==0)return;cancelAnimationFrame(frame);frame=0;drag={id:e.pointerId,x:e.clientX,y:e.clientY,p:position,lastX:e.clientX,time:performance.now(),speed:0,moved:false};velocity=0;});
  deck.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.moved){if(Math.abs(dx)<7||Math.abs(dx)<Math.abs(dy))return;drag.moved=true;deck.setPointerCapture(e.pointerId);}const now=performance.now(),dt=Math.max((now-drag.time)/1000,.008);drag.speed=(drag.lastX-e.clientX)/spacing/dt;drag.lastX=e.clientX;drag.time=now;position=drag.p-dx/spacing;target=position;draw();});
  function release(e){if(!drag||e.pointerId!==drag.id)return;if(drag.moved){ignoreUntil=Date.now()+350;const momentum=Math.max(-1.3,Math.min(1.3,drag.speed*.10));target=Math.round(position+momentum);if(deck.hasPointerCapture(e.pointerId))deck.releasePointerCapture(e.pointerId);}else target=Math.round(target);drag=null;animate();}
  deck.addEventListener('pointerup',release);deck.addEventListener('pointercancel',e=>{if(drag){target=Math.round(position);drag=null;animate();}});document.addEventListener('pointerup',release);
  deck.addEventListener('wheel',e=>{if(Math.abs(e.deltaX)<=Math.abs(e.deltaY)&&!e.shiftKey)return;const delta=Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY;if(Math.abs(delta)<1)return;e.preventDefault();target+=Math.max(-1,Math.min(1,delta/180));animate();clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>{target=Math.round(target);animate();},130);},{passive:false});
  $('.deck-hint',root).textContent='DRAG · SWIPE · ← → / 横スクロール・Shift＋ホイールでチャンネル選択';
  new ResizeObserver(measure).observe(deck);const observer=new IntersectionObserver(([entry])=>{active=entry.isIntersecting;if(active){draw();if(Math.abs(target-position)>.0005)animate();}else {cancelAnimationFrame(frame);frame=0;}},{rootMargin:'80px'});observer.observe(root);controllers.push({root,pause:()=>{active=false;cancelAnimationFrame(frame);frame=0;},resume:()=>{active=root.getBoundingClientRect().bottom>0&&root.getBoundingClientRect().top<innerHeight;if(active)animate();}});choose(music?'music':'all');
 }
 const initObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){initBoutique(e.target);initObserver.unobserve(e.target);}});},{rootMargin:'220px'});document.querySelectorAll('.boutique').forEach(b=>initObserver.observe(b));
 const projectGrid=$('#project-grid'),projectTabs=$('#project-tabs');const projects=data.works.filter(w=>!w.youtube.length);
 function renderProjects(id){projectGrid.replaceChildren();projects.filter(w=>id==='all'||w.genre===id).forEach((w,i)=>{const b=element('button','project-card genre-'+w.genre);b.type='button';b.append(element('span','project-number',String(i+1).padStart(2,'0')),element('span','project-ornament',w.genre==='fantasy'?'✳':w.genre==='commercial'?'✿':w.genre==='action'?'↗':'♡'),element('span','eyebrow',genre(w.genre).label),element('h3','',w.title),element('span','project-action','Xで作品を見る ↗'));b.addEventListener('click',()=>openWork(w));projectGrid.append(b);});projectTabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===id)));}
 data.genres.filter(g=>g.id==='all'||projects.some(w=>w.genre===g.id)).forEach(g=>{const b=element('button','genre-tab',g.label);b.type='button';b.dataset.filter=g.id;b.addEventListener('click',()=>renderProjects(g.id));projectTabs.append(b);});renderProjects('all');
 let artCount=0;const artFiles=Array.from({length:82},(_,i)=>i+1).filter(i=>i!==78);
 function moreArt(){const group=artFiles.slice(artCount,artCount+12);group.forEach(n=>{const b=element('button','gallery-item');b.type='button';b.setAttribute('aria-label','イラスト '+n+' を拡大');const img=element('img');img.src=`assets/thumbs/${n}.webp`;img.alt=`Bianca Illustration ${n}`;img.loading='lazy';img.decoding='async';img.width=320;img.height=320;b.append(img);b.addEventListener('click',()=>{$('#modalImage').src=`assets/illustrations/${n}.jpg`;$('#imageModal').showModal();});$('#gallery').append(b);});artCount+=group.length;$('#more-art').hidden=artCount>=artFiles.length;}
 $('#more-art').addEventListener('click',moreArt);const galleryObserver=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){moreArt();galleryObserver.disconnect();}},{rootMargin:'180px'});galleryObserver.observe($('#gallery'));
 const rooms=[...document.querySelectorAll('main>.room')];let scrollFrame=0;
 function updateRooms(){scrollFrame=0;const records=rooms.map(room=>({room,rect:room.getBoundingClientRect()}));let current=records[0].room;for(const {room,rect} of records){const visible=rect.bottom>0&&rect.top<innerHeight;room.classList.toggle('in-view',visible);if(visible&&!motion.matches)room.style.setProperty('--travel',String(Math.max(-1,Math.min(1,(innerHeight/2-rect.top)/(rect.height+innerHeight/2)))));if(rect.top<=innerHeight*.38&&rect.bottom>innerHeight*.38)current=room;}$('#current-room').textContent=current.dataset.room;document.body.style.setProperty('--scene-color',current.dataset.tint);document.querySelectorAll('.room-navigation a,nav a').forEach(a=>{const chosen=a.hash==='#'+current.id;a.classList.toggle('active',chosen);if(chosen)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
 const queueScroll=()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateRooms);};addEventListener('scroll',queueScroll,{passive:true});addEventListener('resize',queueScroll,{passive:true});motion.addEventListener('change',()=>{controllers.forEach(c=>c.resume());queueScroll();});updateRooms();document.addEventListener('visibilitychange',()=>controllers.forEach(c=>document.hidden?c.pause():c.resume()));
 // Player is loaded only after the viewer deliberately chooses PLAY.

 const dialog=$('#playerDialog'),mount=$('#playerMount'),loading=$('.loading-cover',dialog),status=$('#playerStatus');
 let player=null,request=0,timeout=null,apiPromise=null,returnFocus=null,loadingVideo=null;
 function stopVideo(){if(loadingVideo){loadingVideo.pause();loadingVideo.removeAttribute('src');loadingVideo.load();loadingVideo.remove();loadingVideo=null;}}
 function reveal(){loading.hidden=true;stopVideo();}
 function dispose(){request++;clearTimeout(timeout);if(player){player.destroy();player=null;}mount.replaceChildren();stopVideo();}
 function api(){if(window.YT?.Player)return Promise.resolve(window.YT);if(apiPromise)return apiPromise;
  apiPromise=new Promise((resolve,reject)=>{window.onYouTubeIframeAPIReady=()=>resolve(window.YT);const s=element('script');s.src='https://www.youtube.com/iframe_api';s.onerror=()=>{s.remove();apiPromise=null;reject(new Error('YouTube API unavailable'));};document.head.append(s);});return apiPromise;}
 function outbound(url,text){const a=element('a','source-link',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
 async function play(work,videoId){
  dispose();const token=request;loading.hidden=false;status.textContent='';mount.append(element('div'));mount.firstChild.id='youtubePlayer';
  loading.style.backgroundImage=work.thumbnail?`linear-gradient(#0008,#000b),url("${work.thumbnail}")`:'';
  const clip=genre(work.genre).loading;
  if(clip&&!reduced){loadingVideo=element('video','loading-video');loadingVideo.muted=true;loadingVideo.loop=true;loadingVideo.playsInline=true;loadingVideo.preload='none';loadingVideo.src=clip;loadingVideo.addEventListener('error',stopVideo,{once:true});loading.prepend(loadingVideo);loadingVideo.play().catch(()=>{});}
  timeout=setTimeout(()=>{if(token!==request)return;reveal();status.textContent='読み込みに時間がかかっています。YouTubeで見ることもできます。';},10000);
  try{const YT=await api();if(token!==request||!dialog.open)return;
   player=new YT.Player('youtubePlayer',{host:'https://www.youtube-nocookie.com',videoId,playerVars:{autoplay:1,playsinline:1,rel:0,origin:location.origin},events:{onReady:e=>{if(token!==request)return;clearTimeout(timeout);reveal();e.target.playVideo();},onStateChange:e=>{if(token===request&&e.data===1){clearTimeout(timeout);reveal();status.textContent='';}},onError:()=>{if(token!==request)return;clearTimeout(timeout);reveal();status.textContent='この動画は埋め込みで再生できません。下のYouTubeリンクからご覧ください。';}}});
  }catch(e){if(token!==request)return;clearTimeout(timeout);reveal();status.textContent='プレイヤーを読み込めませんでした。下のYouTubeリンクからご覧ください。';}
 }
 function openWork(work){
  returnFocus=document.activeElement;dispose();$('#playerTitle').textContent=work.title;$('#playerGenre').textContent=genre(work.genre).label;$('#playerDescription').textContent=work.description;$('#playerTools').replaceChildren(...work.tools.map(t=>element('span','tool-tag',t)));
  const links=$('#playerLinks');links.replaceChildren();work.youtube.forEach((id,i)=>links.append(outbound('https://www.youtube.com/watch?v='+id,'YouTubeで見る'+(work.youtube.length>1?' '+(i+1):'')+' ↗')));work.links.forEach((url,i)=>links.append(outbound(url,'Xで作品を見る'+(work.links.length>1?' '+(i+1):'')+' ↗')));
  const variants=$('#playerVariants');variants.replaceChildren();if(work.youtube.length>1)work.youtube.forEach((id,i)=>{const b=element('button','variant','FILM '+String(i+1).padStart(2,'0'));b.addEventListener('click',()=>play(work,id));variants.append(b);});
  status.textContent='';dialog.showModal();
  if(work.youtube.length)play(work,work.youtube[0]);else {loading.hidden=true;mount.append(cover(work,false));status.textContent='Xに公開した作品です。下のリンクからご覧ください。';}
 }
 dialog.addEventListener('close',()=>{dispose();returnFocus?.focus();});
 for(const d of document.querySelectorAll('dialog')){$('.dialog-close',d).addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});}
})();
